name: Test And Lint

on:
  push:
    branches: [main, setup-ci]
    paths:
      - ".github/workflows/main.yml"
      - "./TourMate/**/*.swift"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/main.yml"
      - "./TourMate/**/*.swift"

jobs:
  build:

    runs-on: macos-latest

    env:
      platform: iOS Simulator
      device: iPad Air (4th generation)
    
    defaults:
      run:
        working-directory: ./TourMate

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: "13.2.1"

      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod Install
        run: |
          pod repo update
          pod install
          
      - name: Build
        run: xcodebuild -workspace TourMate.xcworkspace -scheme TourMate -configuration Release -sdk ipadsimulator -destination "platform=$platform,name=$device"
        
      - name: Test
        run: xcodebuild -workspace TourMate.xcworkspace -scheme TourMate -sdk ipadsimulator -destination "platform=$platform,name=$device" test

