name: Xcode Build and Test 

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/main.yml"
      - "./TourMate/**/*.swift"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/main.yml"
      - "./TourMate/**/*.swift"

jobs:
  build:
    strategy:
      matrix:
        scheme: ['TourMate']
        workspace: ['TourMate']
        command: ['build-for-testing', 'test-without-building']

    runs-on: macos-latest

    env:
      platform: iOS Simulator
      device: iPad Air (4th generation)
    
    defaults:
      run:
        working-directory: ./TourMate

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: "13.2.1"

      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod Install
        run: |
          pod install
          
      - name: Build
        run: xcodebuild ${{ matrix.command }} -workspace ${{ matrix.workspace }}.xcworkspace -scheme ${{ matrix.scheme }} -destination "platform=$platform,name=$device"
