name: SwiftLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2

#      - name: Lint code using SwiftLint
#        uses: norio-nomura/action-swiftlint@3.2.1
